### ISSUE TITLE
Code problem

### ISSUE THREAD

**Issue by luolai123** [Atharva-05/vt_mpc#1]
Your work is very interesting. When I ran your code on windows system, the following error appeared. I briefly analyzed it and there was no change in uav_pos. Can you explain it
![d6263e570868532c90def83fb293661](https://github.com/user-attachments/assets/20dcdc98-6290-464c-be30-95c9e04d2630)
![54ce82db0a7b1f8e7131a3289f192ff](https://github.com/user-attachments/assets/aca64429-c721-4942-9298-2e0ddefbff98)

**Comment by Atharva-05** [comment]
Hello @luolai123, thank you for your interest!

Did this error occur while running the script as it is?

The error appears when the cubic spline input (independent variable) is non-increasing. In this case, the input to the spline is a sequence of time-steps as defined here:
line 223: `dt = np.arange(0, time_predicted[-1], self.dt_min)` 
Hence, this error would occur when the predicted timesteps have a *non-increasing value*.

The predicted timesteps are an output of the optimization. If it is a non-increasing sequence, it means that the **optimization has failed**. This could be a result of a changes in the problem formulation, making the problem infeasible. I have added a check for this  #(a3b5358189548eaccbb1171c0c8b4fb255c5e273)

Could you send the complete traceback of the error? Also, did you make any changes to the dataset or any of the other parts in the code? Please let me know the changes, and I would be able to debug. Thanks!

**Comment by luolai123** [comment]
Thank you for your reply. I tried to read the code yesterday and I really appreciate that your code is so clean and standardized. My mistake was that my computer did not have the ma97  solver, I tried to use other solvers to study and run the code

![1731640428990](https://github.com/user-attachments/assets/3f2151fc-6592-4771-b938-6c39184a4a5b)
